name: Release

on:
  push:
    branches: [master, feature/*]

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@askuzminov'
          always-auth: true
      - name: Set Branch
        id: branch
        run: |
          BNAME="$(echo -n ${GITHUB_REF##*/} | sed 's#/#-#g' | tr '[:upper:]' '[:lower:]')"
          BID="$GITHUB_RUN_NUMBER-$(date +%s)"
          echo ::set-env name=BRANCH_NAME::$BNAME
          echo ::set-env name=APP_BUILD::$BID-$GITHUB_SHA
          echo ::set-env name=BUILD_ID::$BID
      - name: Setup GIT
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p ~/.ssh
          ssh-keyscan github.com > ~/.ssh/known_hosts
      - name: Install dependencies
        run: npm ci
      - name: Release GITHUB
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ $BRANCH_NAME == 'master' ]]; then
            echo "Release production"
            npm run release
            git push
            git push --tags
          else
            echo "Release canary"
            npm run release -- prerelease=$BRANCH_NAME.$BUILD_ID
          fi
      - name: Publish GITHUB
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ $BRANCH_NAME == 'master' ]]; then
            echo "Publish production"
            npm publish --tag latest --access public --registry https://npm.pkg.github.com
          else
            echo "Publish canary"
            npm publish --tag canary --access public --registry https://npm.pkg.github.com
          fi
      - name: Publish NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ $BRANCH_NAME == 'master' ]]; then
            echo "Publish production"
            # npm publish --tag latest --access public --registry https://registry.npmjs.org
          else
            echo "Publish canary"
            # npm publish --tag canary --access public --registry https://registry.npmjs.org
          fi
